name: generate snk

on:
  schedule:
    - cron: "0 16 * * *" 

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate svg
        uses: Platane/snk@master
        with:
          github_user_name: garyopen1876
          svg_out_path: dist/github-commit-snake.svg
          
      - name: push svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
